[versions]

micronaut = "4.0.0-M4"
micronaut-docs = '2.0.0'
micronaut-test = "4.0.0-M3"

micronaut-serde = "2.0.0-M7"
micronaut-validation = "4.0.0-M7"

groovy = "4.0.11"
kotlin = '1.8.21'
spock = "2.3-groovy-4.0"

managed-zalando-problem="0.27.1"

micronaut-logging = "1.0.0-M2"
[libraries]
micronaut-logging = { module = "io.micronaut.logging:micronaut-logging-bom", version.ref = "micronaut-logging" }
# micronaut boms
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }

managed-zalando-problem = { module = "org.zalando:problem", version.ref = "managed-zalando-problem" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }

#PLUGINS

kotlin-gradle-plugin = { module = 'org.jetbrains.kotlin:kotlin-gradle-plugin', version.ref = 'kotlin' }
kotlin-gradle-allopen = { module = 'org.jetbrains.kotlin:kotlin-allopen', version.ref = 'kotlin' }
